name: deploy-dockerize-run

on: 
  push:
      branches:
        - ci-cd

jobs:
  deploy:
    if: github.event.head_commit.message == 'deploy'
    runs-on: ubuntu-latest
    name: deploy
    steps:
      - name: Deploy to Staging server
        run: ls -la .
      - name: Deploy to Staging server
        uses: easingthemes/ssh-deploy@main
        env:
          SSH_PRIVATE_KEY: ${{ secrets.SSH_PRIVATE_KEY }}
          SOURCE: "."
          REMOTE_HOST: ${{ secrets.SSH_HOST }}
          REMOTE_USER: ${{ secrets.SSH_USER }}
          TARGET: ${{ secrets.FRONT_DEPLOY_PATH }}
  
  dockerize-and-run:
    needs: deploy
    if: github.event.head_commit.message == 'deploy'
    runs-on: ubuntu-latest
    name: 'dockerize and run'
    steps:
      - name: ls -a via ssh
        uses: fifsky/ssh-action@master
        with:
          command: |
            cd /root
            ls -a
          host: ${{ secrets.SSH_HOST }}
          user: ${{ secrets.SSH_USER }}
          key: ${{ secrets.SSH_PRIVATE_KEY}}
